Add git to notebook-integration Dockerfile
Git is required to install detectron2 from GitHub repository.

Error was:
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?